# Indian Telecom Customer Analytics

## 1. Data Preprocessing

### Project Objective
The objective of this notebook is to prepare the telecom customer dataset for analysis through structured data loading, inspection, validation, and preprocessing. This pipeline ensures data quality by handling missing values, identifying duplicates, validating data types, and readying the dataset for Exploratory Data Analysis (EDA) and Business Intelligence reporting.

---

### Key Dataset Features
* **Customer Demographics:** Age, Gender, Dependents, Location (State, City, Pincode)
* **Telecom Partner Information:** Service Provider, Partner Metrics
* **Usage Metrics:** Calls Made, SMS Sent, Data Used
* **Registration Details:** Date of Registration
* **Financial Metrics:** Estimated Salary
* **Target Metric:** Customer Churn Status

In [7]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import plotly.express as px

import warnings
warnings.filterwarnings("ignore")

## Load Dataset

In this step, we import the telecom customer dataset into a pandas DataFrame for further preprocessing and analysis.

In [12]:
import pandas as pd

file_path = "C:/Users/aditi/OneDrive/Desktop/Indian-Telecom-Customer-Analytics/data/telecom.csv"

df = pd.read_csv(file_path)
df.head()

,customer_id,telecom_partner,gender,age,state,city,pincode,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
0,1,Reliance Jio,F,25,Karnataka,Kolkata,755597,2020-01-01,4,124962,44,45,-361,0
1,2,Reliance Jio,F,55,Mizoram,Mumbai,125926,2020-01-01,2,130556,62,39,5973,0
2,3,Vodafone,F,57,Arunachal Pradesh,Delhi,423976,2020-01-01,0,148828,49,24,193,1
3,4,BSNL,M,46,Tamil Nadu,Kolkata,522841,2020-01-01,1,38722,80,25,9377,1
4,5,BSNL,F,26,Tripura,Delhi,740247,2020-01-01,2,55098,78,15,1393,0

### Initial Observation

The dataset contains customer demographic information, telecom usage statistics, registration details, and churn information. The next step is to inspect its structure and validate data quality.

In [15]:
df.shape

(243553, 14)

In [17]:
print(f"Number of Rows    : {df.shape[0]}")
print(f"Number of Columns : {df.shape[1]}")

Number of Rows    : 243553
Number of Columns : 14

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243553 entries, 0 to 243552
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   customer_id           243553 non-null  int64
 1   telecom_partner       243553 non-null  object
 2   gender                243553 non-null  object
 3   age                   243553 non-null  int64
 4   state                 243553 non-null  object
 5   city                  243553 non-null  object
 6   pincode               243553 non-null  int64
 7   date_of_registration  243553 non-null  object
 8   num_dependents        243553 non-null  int64
 9   estimated_salary      243553 non-null  int64
 10  calls_made            243553 non-null  int64
 11  sms_sent              243553 non-null  int64
 12  data_used             243553 non-null  int64
 13  churn                 243553 non-null  int64
dtypes: int64(9), object(5)
memory usage: 26.0+ MB

In [21]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
customer_id,243553.0,121777.000000,70307.839393,1.0,60889.0,121777.0,182665.0,243553.0
age,243553.0,46.077609,16.444029,18.0,32.0,46.0,60.0,74.0
pincode,243553.0,549501.270541,259808.860574,100006.0,324586.0,548112.0,774994.0,999987.0
num_dependents,243553.0,1.997500,1.414941,0.0,1.0,2.0,3.0,4.0
estimated_salary,243553.0,85021.137839,37508.963233,20000.0,52585.0,84990.0,117488.0,149999.0
calls_made,243553.0,49.010548,29.453556,-10.0,24.0,49.0,74.0,108.0
sms_sent,243553.0,23.945404,14.733575,-5.0,11.0,24.0,36.0,53.0
data_used,243553.0,4993.186025,2942.019547,-987.0,2490.0,4987.0,7493.0,10991.0
churn,243553.0,0.200478,0.400359,0.0,0.0,0.0,0.0,1.0

## Checking Missing Values

Missing values can affect the accuracy of analysis and machine learning models. This step identifies whether any columns contain null values.

In [24]:
df.isnull().sum()

customer_id             0
telecom_partner         0
gender                  0
age                     0
state                   0
city                    0
pincode                 0
date_of_registration    0
num_dependents          0
estimated_salary        0
calls_made              0
sms_sent                0
data_used               0
churn                   0
dtype: int64

In [26]:
(df.isnull().sum()/len(df))*100

customer_id             0.0
telecom_partner         0.0
gender                  0.0
age                     0.0
state                   0.0
city                    0.0
pincode                 0.0
date_of_registration    0.0
num_dependents          0.0
estimated_salary        0.0
calls_made              0.0
sms_sent                0.0
data_used               0.0
churn                   0.0
dtype: float64

## Checking Duplicate Records

Duplicate records can bias statistical analysis and should be identified before proceeding.

In [29]:
df.duplicated().sum()

0

In [36]:
(df["calls_made"] < 0).sum()

6713

In [38]:
(df["sms_sent"] < 0).sum()

7375

In [40]:
(df["data_used"] < 0).sum()

6050

## Data Validation

The dataset is validated by checking:

- Data types
- Missing values
- Duplicate records
- Overall structure

The SQL preprocessing phase has already handled datatype conversion, removal of invalid values, and primary key validation. This notebook confirms the cleaned dataset is ready for exploratory analysis.

In [34]:
df.head()

,customer_id,telecom_partner,gender,age,state,city,pincode,date_of_registration,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
0,1,Reliance Jio,F,25,Karnataka,Kolkata,755597,2020-01-01,4,124962,44,45,-361,0
1,2,Reliance Jio,F,55,Mizoram,Mumbai,125926,2020-01-01,2,130556,62,39,5973,0
2,3,Vodafone,F,57,Arunachal Pradesh,Delhi,423976,2020-01-01,0,148828,49,24,193,1
3,4,BSNL,M,46,Tamil Nadu,Kolkata,522841,2020-01-01,1,38722,80,25,9377,1
4,5,BSNL,F,26,Tripura,Delhi,740247,2020-01-01,2,55098,78,15,1393,0

## Remove Negative Values

In [44]:
df = df[
    (df["calls_made"] >= 0) &
    (df["sms_sent"] >= 0) &
    (df["data_used"] >= 0)
]

## Convert Date Column

In [49]:
df["date_of_registration"] = pd.to_datetime(df["date_of_registration"])

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 223966 entries, 1 to 243552
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   customer_id           223966 non-null  int64
 1   telecom_partner       223966 non-null  object
 2   gender                223966 non-null  object
 3   age                   223966 non-null  int64
 4   state                 223966 non-null  object
 5   city                  223966 non-null  object
 6   pincode               223966 non-null  int64
 7   date_of_registration  223966 non-null  datetime64[ns]
 8   num_dependents        223966 non-null  int64
 9   estimated_salary      223966 non-null  int64
 10  calls_made            223966 non-null  int64
 11  sms_sent              223966 non-null  int64
 12  data_used             223966 non-null  int64
 13  churn                 223966 non-null  int64
dtypes: datetime64[ns](1), int64(9), object(4)
memory usage: 25.6+ MB

## Export Clean Dataset

In [60]:
df.to_csv("telecom_customer_cleaned.csv", index=False)

In [ ]:
## Data Cleaning Summary

The following preprocessing steps were completed successfully:

- Loaded the dataset
- Checked the dataset structure
- Verified missing values
- Removed duplicate records
- Identified and removed records containing negative usage values
- Converted the registration date to datetime format
- Validated data types
- Generated descriptive statistics
- Exported the cleaned dataset for exploratory data analysis